Repository ProjectEssentials/ProjectEssentials-Permissions, pull requests merged in 2019-10, with the labels that each got.

#14 Added Serbian translation
  src/main/resources/assets/projectessentialspermissions/lang/sr_rs.json
Labels: localization thread

#15 Bumped kotlinxSerialization and dokka versions
  gradle.properties
Labels: update dependencies

#16 added german support
  src/main/resources/assets/projectessentialspermissions/lang/de_de.json
Labels: localization thread

#18 Improve documentation wording
  documentation/in-using.md
  readme.md
Labels: documentation
